#ifndef EXAMEN_CLINICO_DOCUMENTO_H
#define EXAMEN_CLINICO_DOCUMENTO_H

#include <string>
#include <fstream>
#include <cstdlib>

using namespace std;

class examen_clinico_documento
{
    private:
    string breathingkind;
    string frecuency;
    string retracciones;
    string abovedamientos;
    string palpaciomobility;
    string vocalvibrations;
    string auscultation;
    string auscultation2;
    string adomenpiel;
    string deformation;
    string mobility;
    string collateralcirculation;
    string palpaciopared;
    string sensitivity;
    string powercrunch;
    string painpoint;
    string deeppalpation;
    string percussion;
    string percussion2;
    string liver;
    string spleen;
    string vaginaltouch;
    string analtouch;
    string genitals;
    string neurological;
    string diagnosticimpressions;
    string talla;
    string peso;
    string pesoHabitual;
    string biotipo;
    string temp;
    string pulso;
    string resp;
    string estadoGeneral;
    string mental;
    string facies;
    string pielAnexos;
    string color;
    string celularSubcutaneo;
    string oteoMioArticular;
    string sistemaLinfatico;
    string cabeza;
    string ojos;
    string pupilas;
    string fondoOjos;
    string nariz;
    string oidos;
    string labios;
    string mucosas;
    string lengua;
    string dientes;
    string paladar;
    string amigdalasFaringe;
    string cuello;
    string tiroides;
    string torax;
    string mamas;
    string cardiovascularPresionArterial;
    string pulsoFrecuencia;
    string ritmo;
    string amplitud;
    string pared;
    string pulsoCardiaco;
    string femoral;
    string pedio;
    string otros;
    string corazonChoquePunta;
    string ruidosCardiacos;
    string soplos;
    string ruidosAdventicios;

    string medic;
    string lastname;
    string name;
    string service;
    string clinicHistory;
    string bed;

public:
       examen_clinico_documento();
        void setbreathingkind(string a);
        void setfrecuency(string a);
        void setretracciones(string a);
        void setabovedamientos(string a);
        void setpalpaciomobility(string a);
        void setvocalvibrations(string a);
        void setpercussion(string a);
        void setpercussion2(string a);
        void setauscultation(string a);
        void setauscultation2(string a);
        void setadomenpiel(string a);
        void setdeformation(string a);
        void setmobility(string a);
        void setcollateralcirculation(string a);
        void setpalpaciopared(string a);
        void setsensitivity(string a);
        void setpowercrunch(string a);
        void setpainpoint(string a);
        void setdeeppalpation(string a);
        void setliver(string a);
        void setspleen(string a);
        void setvaginaltouch(string a);
        void setanaltouch(string a);
        void setgenitals(string a);
        void setneurological(string a);
        void setdiagnosticimpressions(string a);
        void settalla(string a);
        void setpeso(string a);
        void setpesoHabitual(string a);
        void setbiotipo(string a);
        void settemp(string a);
        void setpulso(string a);
        void setresp(string a);
        void setestadoGeneral(string a);
        void setmental(string a);
        void setfacies(string a);
        void setpielAnexos(string a);
        void setcolor(string a);
        void setcelularSubcutaneo(string a);
        void setoteoMioArticular(string a);
        void setsistemaLinfatico(string a);
        void setcabeza(string a);
        void setojos(string a);
        void setpupilas(string a);
        void setfondoOjos(string a);
        void setnariz(string a);
        void setoidos(string a);
        void setlabios(string a);
        void setmucosas(string a);
        void setlengua(string a);
        void setdientes(string a);
        void setpaladar(string a);
        void setamigdalasFaringe(string a);
        void setcuello(string a);
        void settiroides(string a);
        void settorax(string a);
        void setmamas(string a);
        void setcardiovascularPresionArterial(string a);
        void setpulsoFrecuencia(string a);
        void setritmo(string a);
        void setamplitud(string a);
        void setpared(string a);
        void setpulsoCardiaco(string a);
        void setfemoral(string a);
        void setpedio(string a);
        void setotros(string a);
        void setcorazonChoquePunta(string a);
        void setruidosCardiacos(string a);
        void setsoplos(string a);
        void setruidosAdventicios(string a);
        void generateLatex();
        void setmedic(string a);
        void setlastname(string a);
        void setname(string a);
        void setservice(string a);
        void setclinicHistory(string a);
        void setbed(string a);



        string gettalla();
        string getpeso();
        string getpesoHabitual();
        string getbiotipo();
        string gettemp();
        string getpulso();
        string getresp();
        string getestadoGeneral();
        string getmental();
        string getfacies();
        string getpielAnexos();
        string getcolor();
        string getcelularSubcutaneo();
        string getoteoMioArticular();
        string getsistemaLinfatico();
        string getcabeza();
        string getojos();
        string getpupilas();
        string getfondoOjos();
        string getnariz();
        string getoidos();
        string getlabios();
        string getmucosas();
        string getlengua();
        string getdientes();
        string getpaladar();
        string getamigdalasFaringe();
        string getcuello();
        string gettiroides();
        string gettorax();
        string getmamas();
        string getcardiovascularPresionArterial();
        string getpulsoFrecuencia();
        string getritmo();
        string getamplitud();
        string getpared();
        string getpulsoCardiaco();
        string getfemoral();
        string getpedio();
        string getotros();
        string getcorazonChoquePunta();
        string getruidosCardiacos();
        string getsoplos();
        string getruidosAdventicios();
        string getbreathingkind();
        string getfrecuency();
        string getretracciones();
        string getabovedamientos();
        string getpalpaciomobility();
        string getvocalvibrations();
        string getpercussion();
        string getpercussion2();
        string getauscultation();
        string getauscultation2();
        string getadomenpiel();
        string getdeformation();
        string getmobility();
        string getcollateralcirculation();
        string getpalpaciopared();
        string getsensitivity();
        string getpowercrunch();
        string getpainpoint();
        string getdeeppalpation();
        string getliver();
        string getspleen();
        string getvaginaltouch();
        string getanaltouch();
        string getgenitals();
        string getneurological();
        string getdiagnosticimpressions();

};
#endif // EXAMEN_CLINICO_DOCUMENTO_H
